services:
  postgres:
    image: postgres:17-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: bond-bd
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  backend:
    build:
      context: .
      target: dev
    container_name: bond-back
    restart: always
    command: sh -c "npm install && npx prisma generate &&  npm run start:dev"
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - nest_network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
        - action: sync+restart
          path: ./prisma/schema.prisma
          target: /usr/src/app/prisma/schema.prisma
        - action: rebuild
          path: package.json

volumes:
  postgres_data:

networks:
  nest_network:
    driver: bridge
